name: "Compilacion del documento .tex de la carpeta search"

on:
  push:
  branches:
  - main # Detecta cambios en el repositorio principal

permissions:
  contents: write #Esto de permiso de escritura

jobs:
  release_cv:
  name: "Ejecucion Informe LaTex"
  runs-on: ubuntu-latest

  steps:
  name: "Checkout master"
  uses: actions/checkout@v1

  name: "Compilacion del informe"
  uses: xu-cheng/latex-action@master
  with:
  root_file: Scripts/Informe01.tex 

  name: "Revvision del PDF"
  run: |
  file Informe01.pdf | grep -q 'PDF'

  name: "Carga del PDF a una URL fija"
  uses: marvinpinto/action-automatic-releases@latest
  with: 
    repo_token: {{secrets.PERSONAL_ACCESS_TOKEN}}
    automatic_release_tag: "latest"
    prerelease: true
    title: "Carga"
    files: |
    Informe01.pdf
